theme: jekyll-theme-minimal
title: Sudarshan's Homepage
description: I am a post-doc at the University of California, Berkeley. During my PhD, I worked on computational and theoretical catalysis. I am interested in developing new computational methods to understand the fundamentals of catalysis and develop new catalysts of applications in energy storage.